version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: silkroad-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silkroad_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  servicio-cuentas:
      build: ./servicio-cuentas
      image: servicio-cuentas:v1
      container_name: contenedor-cuentas
      restart: always
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/silkroad_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      depends_on:
        - mysqldb

  servicio-foro:
      build: ./servicio-foro
      image: servicio-foro:v1
      container_name: contenedor-foro
      restart: always
      ports:
        - "8081:8081"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/silkroad_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      depends_on:
        - mysqldb

  servicio-juego:
    image: liucho/servicio-juego:v1
    container_name: contenedor-juego
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/silkroad_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
        - mysqldb

volumes:
  mysql_data: